# Generated by Django 2.0.5 on 2021-07-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Step', models.CharField(default='0', max_length=200)),
                ('Description', models.CharField(default='0', max_length=200)),
                ('Result', models.CharField(default='0', max_length=200)),
            ],
        ),
    ]
