# Generated by Django 2.0.5 on 2021-07-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0002_steps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Steps',
        ),
    ]
