# Generated by Django 2.0.5 on 2021-07-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0003_delete_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='rate',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='i1',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='i2',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='i3',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='ic1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='ic2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='ic3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='message',
            field=models.TextField(default='None'),
        ),
    ]
