# Generated by Django 2.0.5 on 2021-07-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0004_auto_20210722_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='i1',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ic1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
