# Generated by Django 2.0.5 on 2021-07-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0005_auto_20210722_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='i1',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='i2',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='i3',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='ic1',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='ic2',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='ic3',
        ),
        migrations.AddField(
            model_name='invoice',
            name='i2',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='i3',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ic2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ic3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
